[client]
showSidebarNavigation = false  # Disables default sidebar nav

[theme]
base = "light"
primaryColor = "#4a6bff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333f"
